# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import embed_pb2 as embed__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShoalEmbedStub:
    """ShoalEmbed is the gRPC service for the embedded storage engine.
    It exposes table management, writes, scans, compaction, and status.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTable = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/CreateTable',
                request_serializer=embed__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=embed__pb2.CreateTableResponse.FromString,
                _registered_method=True)
        self.CreateTableV2 = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/CreateTableV2',
                request_serializer=embed__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=embed__pb2.CreateTableResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/Write',
                request_serializer=embed__pb2.WriteRequest.SerializeToString,
                response_deserializer=embed__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.ConditionalWrite = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/ConditionalWrite',
                request_serializer=embed__pb2.WriteRequest.SerializeToString,
                response_deserializer=embed__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_stream(
                '/shoal.embed.v1.ShoalEmbed/Scan',
                request_serializer=embed__pb2.ScanRequest.SerializeToString,
                response_deserializer=embed__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.ScanV2 = channel.unary_stream(
                '/shoal.embed.v1.ShoalEmbed/ScanV2',
                request_serializer=embed__pb2.ScanRequest.SerializeToString,
                response_deserializer=embed__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.Flush = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/Flush',
                request_serializer=embed__pb2.FlushRequest.SerializeToString,
                response_deserializer=embed__pb2.FlushResponse.FromString,
                _registered_method=True)
        self.Compact = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/Compact',
                request_serializer=embed__pb2.CompactRequest.SerializeToString,
                response_deserializer=embed__pb2.CompactResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/shoal.embed.v1.ShoalEmbed/Status',
                request_serializer=embed__pb2.StatusRequest.SerializeToString,
                response_deserializer=embed__pb2.StatusResponse.FromString,
                _registered_method=True)


class ShoalEmbedServicer:
    """ShoalEmbed is the gRPC service for the embedded storage engine.
    It exposes table management, writes, scans, compaction, and status.
    """

    def CreateTable(self, request, context):
        """CreateTable creates a new table with optional split points.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTableV2(self, request, context):
        """CreateTableV2 enforces the safety-critical default_embedding field. New
        clients use this RPC for embedding-bearing tables so pre-V2 servers fail
        closed with UNIMPLEMENTED rather than ignoring the field.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write writes an unconditional batch of mutations to a table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConditionalWrite(self, request, context):
        """ConditionalWrite atomically evaluates optional per-mutation conditions
        and writes accepted mutations. A separate RPC makes mixed-version clients
        fail closed: servers predating conditional writes return UNIMPLEMENTED
        instead of ignoring unknown condition fields and writing unconditionally.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Scan reads cells from a table. Results are streamed back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanV2(self, request, context):
        """ScanV2 enforces safety-critical vector embedding-space identity. Clients
        issuing vector_search must use this RPC so pre-V2 servers fail closed with
        UNIMPLEMENTED rather than ignoring the embedding_space field.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Flush(self, request, context):
        """Flush forces memtables to RFiles for a table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Compact(self, request, context):
        """Compact runs major compaction on a table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status returns engine metadata (table list, etc.).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShoalEmbedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=embed__pb2.CreateTableRequest.FromString,
                    response_serializer=embed__pb2.CreateTableResponse.SerializeToString,
            ),
            'CreateTableV2': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTableV2,
                    request_deserializer=embed__pb2.CreateTableRequest.FromString,
                    response_serializer=embed__pb2.CreateTableResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=embed__pb2.WriteRequest.FromString,
                    response_serializer=embed__pb2.WriteResponse.SerializeToString,
            ),
            'ConditionalWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ConditionalWrite,
                    request_deserializer=embed__pb2.WriteRequest.FromString,
                    response_serializer=embed__pb2.WriteResponse.SerializeToString,
            ),
            'Scan': grpc.unary_stream_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=embed__pb2.ScanRequest.FromString,
                    response_serializer=embed__pb2.ScanResponse.SerializeToString,
            ),
            'ScanV2': grpc.unary_stream_rpc_method_handler(
                    servicer.ScanV2,
                    request_deserializer=embed__pb2.ScanRequest.FromString,
                    response_serializer=embed__pb2.ScanResponse.SerializeToString,
            ),
            'Flush': grpc.unary_unary_rpc_method_handler(
                    servicer.Flush,
                    request_deserializer=embed__pb2.FlushRequest.FromString,
                    response_serializer=embed__pb2.FlushResponse.SerializeToString,
            ),
            'Compact': grpc.unary_unary_rpc_method_handler(
                    servicer.Compact,
                    request_deserializer=embed__pb2.CompactRequest.FromString,
                    response_serializer=embed__pb2.CompactResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=embed__pb2.StatusRequest.FromString,
                    response_serializer=embed__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shoal.embed.v1.ShoalEmbed', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shoal.embed.v1.ShoalEmbed', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShoalEmbed:
    """ShoalEmbed is the gRPC service for the embedded storage engine.
    It exposes table management, writes, scans, compaction, and status.
    """

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/CreateTable',
            embed__pb2.CreateTableRequest.SerializeToString,
            embed__pb2.CreateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTableV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/CreateTableV2',
            embed__pb2.CreateTableRequest.SerializeToString,
            embed__pb2.CreateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/Write',
            embed__pb2.WriteRequest.SerializeToString,
            embed__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConditionalWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/ConditionalWrite',
            embed__pb2.WriteRequest.SerializeToString,
            embed__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/Scan',
            embed__pb2.ScanRequest.SerializeToString,
            embed__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/ScanV2',
            embed__pb2.ScanRequest.SerializeToString,
            embed__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Flush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/Flush',
            embed__pb2.FlushRequest.SerializeToString,
            embed__pb2.FlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Compact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/Compact',
            embed__pb2.CompactRequest.SerializeToString,
            embed__pb2.CompactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shoal.embed.v1.ShoalEmbed/Status',
            embed__pb2.StatusRequest.SerializeToString,
            embed__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
